# Generated by Django 2.0.6 on 2018-06-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_office', '0006_attachment_mimetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='пример: Недельная рассылка о главном', max_length=255, verbose_name='Назвагте рассылки: ')),
                ('last_send', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('once', 'Один раз'), ('daily', 'Каждый день'), ('weekly', 'Каждую неделю'), ('monthly', 'Каждый месяц')], default='once', help_text='Как часто будет срабатывать рассылка.', max_length=20, null=True)),
                ('start_date', models.DateField()),
                ('paused', models.BooleanField(default=False)),
                ('stopped', models.BooleanField(default=False)),
                ('sent', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post_office.EmailTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
