# Generated by Django 2.0.6 on 2018-06-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtask',
            name='frequency',
            field=models.CharField(choices=[('once', 'Один раз'), ('daily', 'Каждый день'), ('weekly', 'Каждую неделю'), ('monthly', 'Каждый месяц')], default='once', help_text='Как часто будет срабатывать рассылка.', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='name',
            field=models.CharField(help_text='пример: Недельная рассылка о главном', max_length=255, verbose_name='Название рассылки: '),
        ),
    ]
